sudo: false

language: python
python:
  - "3.6"

env:
  global:
    - DB_URL="sqlite:///dev.db"
    - TEST_DB_URL="sqlite:///test.db"
    - PYTHONPATH=.

install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install -e .

before_script:
  - flake8 koob tests

script:
  - py.test -v tests --cov koob --cov-report term-missing
